[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"

# Cron job configuration
[cron]
# Run daily at 12:50 PM UTC (6:20 PM IST) - same as your current GitHub Actions schedule
schedule = "50 12 * * *"
command = "python main.py"

[environments.production]
# Railway will automatically detect Python and install requirements.txt
